### ISSUE TITLE
implements Moodle coding style

### ISSUE THREAD

**Issue by ak4t0sh** [svsarun844/marquee#2]
Once #1 done it will give you feedback about issues in your code. Fix reported issues then check https://docs.moodle.org/dev/Plugin_contribution_checklist

**Comment by svsarun844** [comment]
To add css as different css file format to follow in moodle standard to call css

**Comment by ak4t0sh** [comment]
Why closing this issue ? Please check https://docs.moodle.org/dev/Plugin_contribution_checklist
And test your plugin with a recent Moodle version (at least 3.5) in debug mode https://docs.moodle.org/36/en/Debugging
You'll see a lot of warning an error appears.

Example in add.php : 

![image](https://user-images.githubusercontent.com/2222386/55397600-e46e0d00-5546-11e9-9b26-51ac5f084f44.png)
